### ISSUE TITLE
No volume/artwork

### ISSUE THREAD

**Issue by lparsonsp** [danbee/persephone#58]
Any ideas how to unmute audio and view album artwork? Thanks for a great looking OSX app! 
![Untitled](https://user-images.githubusercontent.com/64394877/80335717-03060c80-880a-11ea-8572-4245a38fa58e.jpeg)
Edit: It appears to be an MPD issue as I am having the same problem in another client. Please disregard.

**Comment by MonsieurPommesFrites** [comment]
I also don't have artwork, but on the M.A.L.P. client on Android the artwork is correctly displayed. Also, certain songs don't show up in the library, whereas again on the Android app they are visible. 

Otherwise, many thanks for a great app!

**Comment by danbee** [comment]
@lparsonsp For the volume control to work you probably need to add the line `mixer_type "software"` to your audio output configuration in MPD.

I'm not sure why you're not getting album art. What version of MPD are you running? The ability to fetch album art was a fairly recent addition.

**Comment by danbee** [comment]
It looks like M.A.L.P. fetches album art from the internet via MusicBrainz and other similar services. Persephone doesn't do that yet. You'll need to have album art in each album directory named "cover.jpg" or "folder.jpg" so that MPD can send it along to the client.

Also, Persephone is very album focused which might explain why some tracks are not displaying. Can you give me some more details about the tracks you're not seeing? Are they tracks within albums or just single songs?

**Comment by lparsonsp** [comment]
> @lparsonsp For the volume control to work you probably need to add the line `mixer_type "software"` to your audio output configuration in MPD.
> 
> I'm not sure why you're not getting album art. What version of MPD are you running? The ability to fetch album art was a fairly recent addition.

I don't have the album art as a separate file so that's the issue there. No problem. 

`mixer_type "software"` worked for volume control.

Does persephone output audio (maybe via httpd?) if the mpd server is on a remote desktop or is it simply used as a controller if you had the mpd server on your local machine? Maybe I'm misunderstanding the purpose of the application. Thanks!

**Comment by MonsieurPommesFrites** [comment]
Thanks Dan for getting back to me. I'm running mpd version 0.21.5 on armbian. I do not have album artwork in the directories. I'll look for a script that downloads the artwork. 

I am missing a whole album. The band name contains an &, not sure, but that's maybe a reason for the error.

**Comment by MonsieurPommesFrites** [comment]
My bad, the missing album was a metadata issue. Once I adjusted the metadata, the album showed up.

**Comment by danbee** [comment]
@MonsieurPommesFrites What was the problem with your metadata? I'd like to know because it's possible I'm doing something in Persephone that's breaking things.

**Comment by MonsieurPommesFrites** [comment]
I decided to organize my whole library using the linux tool beets. Once I did the beets import (which modified metadata) the album showed up on Persephone. Unfortunately I don't know exactly what changed, as I don't have the old files anymore.

**Comment by Nemo157** [comment]
One thing I've noticed is that the next version of MPD adds a new `readpicture` command to get artwork from the file metadata, so that you don't need a separate album art file. It should be possible for Persephone to try and request `albumart` first then fallback to `readpicture` if that doesn't exist.
